### ISSUE TITLE
Submission gives error with possesive case

### ISSUE THREAD

**Issue by 0xGGGGG** [yogurt-cultures/laktoz#3]
I am trying to construct this term:

`http://laktoz.yogurtcultures.org/?subject=ahmet&case=possesive&predicate=ev&whom=first_person_singular`

After submission page gives an error with the stacktrace:

```
builtins.TypeError
TypeError: possesive() missing 1 required positional argument: 'person'

Traceback (most recent call last)
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/arguman/env/laktoz/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/arguman/laktoz/app.py", line 423, in index
result = render_result(request.args)
File "/home/arguman/laktoz/app.py", line 352, in render_result
parts.append((subject_case, case_processor(subject)[len(subject):], colorize(case_processor)))
TypeError: possesive() missing 1 required positional argument: 'person'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

```

Either formation does not make sense, or there is a bug. In any case, it should not give a code error.

**Comment by fatiherikli** [comment]
The problem is possessive function receives the person as "person". It should be "whom" @frumpish
